### ISSUE TITLE
live-premailer adds css styles after inserting variables to template

### ISSUE THREAD

**Issue by GrabowskiM** [turkus/live-premailer#8]
When combining templates with variables and css there is wrong order of applying them to _live.html file. It first inserts variables and than it's parsing css file. Therefore if you have file:
```
<p>My custom paragraph</p>
{{ message_html }}
```
and message_html is: `<p>Message html</p>`
with css:
```
p {
  margin: 0 0 30px;
}
```
exec files xxx_dev_live.html is
```
<p style="margin: 0 0 30px">My custom paragraph</p>
<p style="margin: 0 0 30px">Message html</p>
```
which is wrong, because xxx.html is just
```
<p style="margin: 0 0 30px">My custom paragraph</p>
{{ message_html }}
```
and later when my code inserts there variables
```
<p style="margin: 0 0 30px">My custom paragraph</p>
<p>Message html</p>
```
So my final file is different from _dev_live.html

**Comment by turkus** [comment]
@GrabowskiM thanks for your feedback!
